name: Scaffolding
version: '${version}'
main: com.wolfyscript.scaffolding.loader.spigot.SpigotLoaderPlugin
api-version: 1.21
authors: [ WolfyScript ]
load: STARTUP

libraries:
  - "org.apache.commons:commons-lang3:3.12.0"

loadbefore:
  - ChatColor
  - ChatColor2
  - StackableItems
  - DiSky
  - EpicWorldGenerator

softdepend:
  - Magic
  - LWC
  - PlotSquared
  - WorldGuard
  - MythicMobs
  - MMOItems
  - BungeeChat
  - mcMMO
  - Oraxen
  - ItemsAdder
  - PlaceholderAPI
  - eco
  - zAuctionHouseV3
  - SCore
