name: Scaffolding
version: '${version}'
main: com.wolfyscript.scaffolding.spigot.loader.SpigotLoaderPlugin
api-version: 1.21
authors: [ WolfyScript ]
load: STARTUP

libraries:
  - "org.apache.commons:commons-lang3:3.12.0"
  - "${libs.guice.get()}"
  - "${libs.reflections.get()}"
  - "${libs.fastutil.get()}"
  - "${libs.hocon.get()}"
  - "${libs.jackson.annotations.get()}"
  - "${libs.jackson.core.get()}"
  - "${libs.jackson.databind.get()}"
  - "${libs.adventure.api.get()}"
  - "${libs.adventure.text.minimessage.get()}"
  - "${libs.adventure.platform.bukkit.get()}"
  - "${libs.kotlin.stdlib.get()}"

loadbefore:
  - ChatColor
  - ChatColor2
  - StackableItems
  - DiSky
  - EpicWorldGenerator

softdepend:
  - Magic
  - LWC
  - PlotSquared
  - WorldGuard
  - MythicMobs
  - MMOItems
  - BungeeChat
  - mcMMO
  - Oraxen
  - ItemsAdder
  - PlaceholderAPI
  - eco
  - zAuctionHouseV3
  - SCore
