kotlin.code.style=official
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
group=com.wolfyscript.scafall
version=alpha0.3.0.0
debugPort=5006

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.5-20250325.162830

# Forge
forge_version=55.0.1
forge_loader_version_range=[55,)

# NeoForge
neoforge_version=21.5.4-beta
neoforge_loader_version_range=[4,)