# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
# external plugins
spigot-plugin-score = "4.24.4.15"
spigot-plugin-executableblocks = "4.24.4.15"
spigot-plugin-denizen = "1.2.5-SNAPSHOT"
spigot-plugin-eco = "6.76.2"
spigot-plugin-itemsadder = "3.1.5"
spigot-plugin-oraxen = "1.152.0"
spigot-plugin-magic = "10.2"
spigot-plugin-mythic = "5.9.5"
spigot-plugin-mythiclib = "1.7.1-SNAPSHOT"
spigot-plugin-mmoitems = "6.10.1-SNAPSHOT"
spigot-plugin-placeholderapi = "2.11.6"
## ##

## Sponge Impl dependencies ##
sponge-impl = "1.21.5-15.0.0-SNAPSHOT"

[libraries]
## Spigot Impl dependencies ##
spigot-plugin-score = { module = "com.ssomar.score:SCore", version.ref = "spigot-plugin-score" }
spigot-plugin-executableblocks = { module = "com.ssomar.executableblocks:ExecutableBlocks", version.ref = "spigot-plugin-executableblocks" }
spigot-plugin-denizen = { module = "com.denizenscript:denizen", version.ref = "spigot-plugin-denizen" }
spigot-plugin-eco = { module = "com.willfp:eco", version.ref = "spigot-plugin-eco" }
spigot-plugin-itemsadder = { module = "com.github.LoneDev6:api-itemsadder", version.ref = "spigot-plugin-itemsadder" }
spigot-plugin-oraxen = { module = "com.github.oraxen:oraxen", version.ref = "spigot-plugin-oraxen" }
spigot-plugin-magic = { module = "com.elmakers.mine.bukkit:MagicAPI", version.ref = "spigot-plugin-magic" }
spigot-plugin-mythic = { module = "io.lumine:Mythic-Dist", version.ref = "spigot-plugin-mythic" }
spigot-plugin-mythiclib = { module = "io.lumine:MythicLib-dist", version.ref = "spigot-plugin-mythiclib" }
spigot-plugin-mmoitems = { module = "net.Indyuce:MMOItems-API", version.ref = "spigot-plugin-mmoitems" }
spigot-plugin-placeholderapi = { module = "me.clip:placeholderapi", version.ref = "spigot-plugin-placeholderapi" }

## Sponge Impl dependencies ##
spongepowered-impl = { module = "org.spongepowered:sponge", version.ref = "sponge-impl" }

[bundles]
spigot-external-plugins = [
    "spigot-plugin-score",
    "spigot-plugin-denizen",
    "spigot-plugin-eco",
    "spigot-plugin-executableblocks",
    "spigot-plugin-itemsadder",
    "spigot-plugin-magic",
    "spigot-plugin-mmoitems",
    "spigot-plugin-mythic",
    "spigot-plugin-mythiclib",
    "spigot-plugin-oraxen",
    "spigot-plugin-placeholderapi",
]
